// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: emails/emails.proto

package emails

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EmailRecipient struct {
	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EmailAddress string `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
}

func (m *EmailRecipient) Reset()         { *m = EmailRecipient{} }
func (m *EmailRecipient) String() string { return proto.CompactTextString(m) }
func (*EmailRecipient) ProtoMessage()    {}
func (*EmailRecipient) Descriptor() ([]byte, []int) {
	return fileDescriptor_d38f2eb58e1874bc, []int{0}
}
func (m *EmailRecipient) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmailRecipient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmailRecipient.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmailRecipient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRecipient.Merge(m, src)
}
func (m *EmailRecipient) XXX_Size() int {
	return m.Size()
}
func (m *EmailRecipient) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRecipient.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRecipient proto.InternalMessageInfo

func (m *EmailRecipient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmailRecipient) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type SendEmailRequest struct {
	ID          string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Recipients  []EmailRecipient `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients"`
	HtmlContent string           `protobuf:"bytes,3,opt,name=html_content,json=htmlContent,proto3" json:"html_content,omitempty"`
	TextContent string           `protobuf:"bytes,4,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	// Delivery time in UTC, immediate if null
	DeliverAt *time.Time `protobuf:"bytes,5,opt,name=deliver_at,json=deliverAt,proto3,stdtime" json:"deliver_at,omitempty"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d38f2eb58e1874bc, []int{1}
}
func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return m.Size()
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SendEmailRequest) GetRecipients() []EmailRecipient {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *SendEmailRequest) GetHtmlContent() string {
	if m != nil {
		return m.HtmlContent
	}
	return ""
}

func (m *SendEmailRequest) GetTextContent() string {
	if m != nil {
		return m.TextContent
	}
	return ""
}

func (m *SendEmailRequest) GetDeliverAt() *time.Time {
	if m != nil {
		return m.DeliverAt
	}
	return nil
}

type SendEmailResponse struct {
	ID          string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sent        bool      `protobuf:"varint,2,opt,name=sent,proto3" json:"sent,omitempty"`
	Scheduled   bool      `protobuf:"varint,3,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	ScheduledAt time.Time `protobuf:"bytes,4,opt,name=scheduled_at,json=scheduledAt,proto3,stdtime" json:"scheduled_at"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d38f2eb58e1874bc, []int{2}
}
func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return m.Size()
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SendEmailResponse) GetSent() bool {
	if m != nil {
		return m.Sent
	}
	return false
}

func (m *SendEmailResponse) GetScheduled() bool {
	if m != nil {
		return m.Scheduled
	}
	return false
}

func (m *SendEmailResponse) GetScheduledAt() time.Time {
	if m != nil {
		return m.ScheduledAt
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*EmailRecipient)(nil), "emails.EmailRecipient")
	proto.RegisterType((*SendEmailRequest)(nil), "emails.SendEmailRequest")
	proto.RegisterType((*SendEmailResponse)(nil), "emails.SendEmailResponse")
}

func init() { proto.RegisterFile("emails/emails.proto", fileDescriptor_d38f2eb58e1874bc) }

var fileDescriptor_d38f2eb58e1874bc = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x8d, 0xbb, 0xa1, 0x6a, 0xa7, 0x05, 0x81, 0x91, 0x56, 0xa1, 0x42, 0x69, 0x29, 0x97, 0x5e,
	0x48, 0xa5, 0x72, 0x45, 0x42, 0x0d, 0x20, 0xb4, 0x12, 0xa7, 0xc0, 0x89, 0x4b, 0x95, 0xc6, 0x43,
	0x6a, 0x29, 0x89, 0x43, 0xec, 0x20, 0x3e, 0x63, 0xbf, 0x82, 0x6f, 0xd9, 0xe3, 0x1e, 0x39, 0x2d,
	0x28, 0xfd, 0x00, 0x7e, 0x01, 0xd9, 0x4e, 0xb2, 0x0b, 0x02, 0xed, 0xa9, 0x33, 0x6f, 0xde, 0x8c,
	0xdf, 0x7b, 0x0d, 0x3c, 0xc4, 0x3c, 0xe6, 0x99, 0x5c, 0xdb, 0x9f, 0xa0, 0xac, 0x84, 0x12, 0x74,
	0x68, 0xbb, 0xd9, 0xb3, 0x94, 0xab, 0x43, 0xbd, 0x0f, 0x12, 0x91, 0xaf, 0x53, 0x91, 0x8a, 0xb5,
	0x19, 0xef, 0xeb, 0x4f, 0xa6, 0x33, 0x8d, 0xa9, 0xec, 0xda, 0x6c, 0x9e, 0x0a, 0x91, 0x66, 0x78,
	0xcd, 0x52, 0x3c, 0x47, 0xa9, 0xe2, 0xbc, 0xb4, 0x84, 0xe5, 0x19, 0xdc, 0x7b, 0xa3, 0x2f, 0x47,
	0x98, 0xf0, 0x92, 0x63, 0xa1, 0x28, 0x05, 0xb7, 0x88, 0x73, 0xf4, 0xc8, 0x82, 0xac, 0xc6, 0x91,
	0xa9, 0xe9, 0x53, 0xb8, 0x6b, 0xde, 0xdf, 0xc5, 0x8c, 0x55, 0x28, 0xa5, 0x37, 0x30, 0xc3, 0xa9,
	0x01, 0xb7, 0x16, 0x5b, 0xfe, 0x22, 0x70, 0xff, 0x3d, 0x16, 0xac, 0xbd, 0xf7, 0xb9, 0x46, 0xa9,
	0xe8, 0x29, 0x0c, 0x38, 0xb3, 0xb7, 0xc2, 0x61, 0x73, 0x35, 0x1f, 0x9c, 0xbd, 0x8e, 0x06, 0x9c,
	0xd1, 0x17, 0x00, 0x55, 0xf7, 0xa4, 0x3e, 0x77, 0xb2, 0x9a, 0x6c, 0x4e, 0x83, 0xd6, 0xf2, 0x9f,
	0x8a, 0x42, 0xf7, 0xe2, 0x6a, 0xee, 0x44, 0x37, 0xf8, 0xf4, 0x09, 0x4c, 0x0f, 0x2a, 0xcf, 0x76,
	0x89, 0x28, 0x14, 0x16, 0xca, 0x3b, 0x31, 0x72, 0x26, 0x1a, 0x7b, 0x65, 0x21, 0x4d, 0x51, 0xf8,
	0x55, 0xf5, 0x14, 0xd7, 0x52, 0x34, 0xd6, 0x51, 0x5e, 0x02, 0x30, 0xcc, 0xf8, 0x17, 0xac, 0x76,
	0xb1, 0xf2, 0xee, 0x2c, 0xc8, 0x6a, 0xb2, 0x99, 0x05, 0x36, 0xb1, 0xa0, 0x4b, 0x2c, 0xf8, 0xd0,
	0x25, 0x16, 0xba, 0xe7, 0x3f, 0xe6, 0x24, 0x1a, 0xb7, 0x3b, 0x5b, 0xb5, 0xfc, 0x46, 0xe0, 0xc1,
	0x0d, 0xc7, 0xb2, 0x14, 0x85, 0xc4, 0xff, 0x5a, 0xa6, 0xe0, 0x4a, 0xad, 0x44, 0x67, 0x37, 0x8a,
	0x4c, 0x4d, 0x1f, 0xc3, 0x58, 0x26, 0x07, 0x64, 0x75, 0x86, 0xcc, 0xb8, 0x18, 0x45, 0xd7, 0x00,
	0x7d, 0x0b, 0xd3, 0xbe, 0xd1, 0x12, 0xdd, 0x5b, 0x25, 0x8e, 0x74, 0x54, 0x46, 0xe6, 0xa4, 0xdf,
	0xdc, 0xaa, 0xcd, 0x3b, 0x18, 0x1a, 0x8d, 0x92, 0x86, 0x30, 0xee, 0x15, 0x53, 0xaf, 0x0b, 0xfc,
	0xef, 0xbf, 0x6d, 0xf6, 0xe8, 0x1f, 0x13, 0x6b, 0x6f, 0xe9, 0x84, 0x8b, 0x8b, 0xc6, 0x27, 0x97,
	0x8d, 0x4f, 0x7e, 0x36, 0x3e, 0x39, 0x3f, 0xfa, 0xce, 0xe5, 0xd1, 0x77, 0xbe, 0x1f, 0x7d, 0xe7,
	0x63, 0xfb, 0x95, 0xee, 0x87, 0x46, 0xda, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x03,
	0x8f, 0x76, 0xcb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailsClient is the client API for Emails service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailsClient interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
}

type emailsClient struct {
	cc *grpc.ClientConn
}

func NewEmailsClient(cc *grpc.ClientConn) EmailsClient {
	return &emailsClient{cc}
}

func (c *emailsClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, "/emails.Emails/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailsServer is the server API for Emails service.
type EmailsServer interface {
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
}

func RegisterEmailsServer(s *grpc.Server, srv EmailsServer) {
	s.RegisterService(&_Emails_serviceDesc, srv)
}

func _Emails_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailsServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emails.Emails/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailsServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Emails_serviceDesc = grpc.ServiceDesc{
	ServiceName: "emails.Emails",
	HandlerType: (*EmailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Emails_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emails/emails.proto",
}

func (m *EmailRecipient) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmailRecipient) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.EmailAddress) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.EmailAddress)))
		i += copy(dAtA[i:], m.EmailAddress)
	}
	return i, nil
}

func (m *SendEmailRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SendEmailRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.Recipients) > 0 {
		for _, msg := range m.Recipients {
			dAtA[i] = 0x12
			i++
			i = encodeVarintEmails(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.HtmlContent) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.HtmlContent)))
		i += copy(dAtA[i:], m.HtmlContent)
	}
	if len(m.TextContent) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.TextContent)))
		i += copy(dAtA[i:], m.TextContent)
	}
	if m.DeliverAt != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintEmails(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeliverAt)))
		n1, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.DeliverAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *SendEmailResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SendEmailResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if m.Sent {
		dAtA[i] = 0x10
		i++
		if m.Sent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Scheduled {
		dAtA[i] = 0x18
		i++
		if m.Scheduled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintEmails(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(m.ScheduledAt)))
	n2, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.ScheduledAt, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	return i, nil
}

func encodeVarintEmails(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *EmailRecipient) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	l = len(m.EmailAddress)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	return n
}

func (m *SendEmailRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	if len(m.Recipients) > 0 {
		for _, e := range m.Recipients {
			l = e.Size()
			n += 1 + l + sovEmails(uint64(l))
		}
	}
	l = len(m.HtmlContent)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	l = len(m.TextContent)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	if m.DeliverAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.DeliverAt)
		n += 1 + l + sovEmails(uint64(l))
	}
	return n
}

func (m *SendEmailResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	if m.Sent {
		n += 2
	}
	if m.Scheduled {
		n += 2
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.ScheduledAt)
	n += 1 + l + sovEmails(uint64(l))
	return n
}

func sovEmails(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozEmails(x uint64) (n int) {
	return sovEmails(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EmailRecipient) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmails
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmailRecipient: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmailRecipient: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmailAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EmailAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEmails(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SendEmailRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmails
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SendEmailRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SendEmailRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipients", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipients = append(m.Recipients, EmailRecipient{})
			if err := m.Recipients[len(m.Recipients)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HtmlContent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HtmlContent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TextContent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TextContent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeliverAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeliverAt == nil {
				m.DeliverAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.DeliverAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEmails(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SendEmailResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmails
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SendEmailResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SendEmailResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Sent = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scheduled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Scheduled = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.ScheduledAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEmails(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEmails(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEmails
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEmails
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthEmails
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEmails
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEmails(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthEmails
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEmails = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEmails   = fmt.Errorf("proto: integer overflow")
)
